default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: <%= ENV.fetch('DATABASE_USER', 'admin') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'admin') %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>


development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME_DEVELOPMENT', 'v360_todo_list_development') %>
  
test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME_TEST', 'v360_todo_list_test') %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> 

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
